# =============================================
# Fichero de Consultas SQL para el Club Náutico
# =============================================

# -- Consultas de SocioRepository --
select-socio-byDni = SELECT dni, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, tiene_titulo_patron, id_inscripcion_fk FROM Socio WHERE dni = ?
insert-socio = INSERT INTO Socio (dni, nombre, apellidos, fecha_nacimiento, direccion, fecha_inscripcion, tiene_titulo_patron, id_inscripcion_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
update-socio-asignarInscripcion = UPDATE Socio SET id_inscripcion_fk = ? WHERE dni = ?
select-sociosByInscripcionId = SELECT * FROM Socio WHERE id_inscripcion_fk = ?
update-socio-tituloPatron = UPDATE Socio SET tiene_titulo_patron = TRUE WHERE dni = ?
select-socios-con-titulo = SELECT * FROM Socio WHERE tiene_titulo_patron = TRUE
select-all-socios-with-titular-status = SELECT s.*, i.dni_socio_titular_fk FROM Socio s LEFT JOIN Inscripcion i ON s.dni = i.dni_socio_titular_fk

# -- Consultas de InscripcionRepository --
insert-inscripcion-individual = INSERT INTO Inscripcion (dni_socio_titular_fk, cuota, fecha_creacion, tipo) VALUES (?, ?, ?, 'INDIVIDUAL')
select-inscripcion-byTitularDni = SELECT id_inscripcion, dni_socio_titular_fk, cuota, fecha_creacion, tipo FROM Inscripcion WHERE dni_socio_titular_fk = ?
update-inscripcion-aFamiliar = UPDATE Inscripcion SET cuota = ?, tipo = 'FAMILIAR' WHERE id_inscripcion = ?
select-inscripciones-listado = SELECT i.id_inscripcion, i.dni_socio_titular_fk, i.cuota, i.fecha_creacion, i.tipo, COUNT(s.dni) as num_familiares \
                               FROM Inscripcion i \
                               LEFT JOIN Socio s ON i.id_inscripcion = s.id_inscripcion_fk AND s.dni != i.dni_socio_titular_fk \
                               GROUP BY i.id_inscripcion, i.dni_socio_titular_fk, i.cuota, i.fecha_creacion, i.tipo
select-inscripciones-by-tipo=SELECT * FROM Inscripcion WHERE tipo = ?

# -- Consultas de PatronRepository --
select-allPatrones = SELECT dni, nombre, apellidos, fecha_nacimiento, fecha_expedicion_titulo FROM Patron
select-patron-byDni = SELECT * FROM Patron WHERE dni = ?
insert-patron = INSERT INTO Patron (dni, nombre, apellidos, fecha_nacimiento, fecha_expedicion_titulo) VALUES (?, ?, ?, ?, ?)
select-embarcacion-byPatron = SELECT * FROM Embarcacion WHERE dni_patron_asignado_fk = ?

# -- Consultas de EmbarcacionRepository --
select-embarcacion-byMatricula = SELECT * FROM Embarcacion WHERE matricula = ?
select-embarcacion-byNombre = SELECT * FROM Embarcacion WHERE nombre = ?
insert-embarcacion = INSERT INTO Embarcacion (matricula, tipo, nombre, plazas, dimensiones, dni_patron_asignado_fk) VALUES (?, ?, ?, ?, ?, ?)
select-allEmbarcaciones = SELECT * FROM Embarcacion
select-embarcacion-byTipo = SELECT * FROM Embarcacion WHERE tipo = ?
update-embarcacion-asociarPatron = UPDATE Embarcacion SET dni_patron_asignado_fk = ? WHERE matricula = ?
select-embarcaciones-disponibles = SELECT * FROM Embarcacion e WHERE NOT EXISTS (SELECT 1 FROM Reserva r WHERE r.matricula_embarcacion_fk = e.matricula AND r.fecha_actividad BETWEEN ? AND ?)
check-alquiler-disponibilidad = SELECT COUNT(*) FROM Alquiler WHERE matricula_embarcacion_fk = ? AND (fecha_inicio <= ? AND fecha_fin >= ?)
check-reserva-disponibilidad = SELECT COUNT(*) FROM Reserva WHERE matricula_embarcacion_fk = ? AND (fecha_actividad BETWEEN ? AND ?)

# -- Consultas de ReservaRepository --
select-reserva-by-matricula-and-fecha = SELECT id_reserva FROM Reserva WHERE matricula_embarcacion_fk = ? AND fecha_actividad = ?
insert-reserva = INSERT INTO Reserva (dni_socio_solicitante_fk, matricula_embarcacion_fk, fecha_actividad, plazas_solicitadas, descripcion, precio_total) VALUES (?, ?, ?, ?, ?, ?)

# -- Consultas de AlquilerRepository --
insert-alquiler = INSERT INTO Alquiler (dni_socio_titular_fk, matricula_embarcacion_fk, fecha_inicio, fecha_fin, precio_total) VALUES (?, ?, ?, ?, ?)
insert-socio-alquiler = INSERT INTO Socio_Alquiler (id_alquiler_fk, dni_socio_fk) VALUES (?, ?)
select-alquileres-futuros = SELECT id_alquiler, dni_socio_titular_fk, matricula_embarcacion_fk, fecha_inicio, fecha_fin, precio_total FROM Alquiler WHERE fecha_inicio >= CURDATE() ORDER BY fecha_inicio ASC

# API-PRACTICA 2 Nuevas consultas
select-all-reservas = SELECT * FROM Reserva
select-reservas-posteriores-fecha = SELECT * FROM Reserva WHERE fecha_actividad > ?
select-reserva-by-id = SELECT * FROM Reserva WHERE id_reserva = ?
check-reserva-embarcacion-disponible = SELECT id_reserva FROM Reserva WHERE matricula_embarcacion_fk = ? AND fecha_actividad = ?
update-reserva-fecha = UPDATE Reserva SET fecha_actividad = ? WHERE id_reserva = ?
update-reserva-datos = UPDATE Reserva SET descripcion = ?, plazas_solicitadas = ?, precio_total = ? WHERE id_reserva = ?
delete-reserva = DELETE FROM Reserva WHERE id_reserva = ?

select-all-alquileres=SELECT * FROM Alquiler
select-alquileres-futuros-parametro=SELECT id_alquiler, dni_socio_titular_fk, matricula_embarcacion_fk, fecha_inicio, fecha_fin, precio_total FROM Alquiler WHERE fecha_inicio >= ? ORDER BY fecha_inicio ASC
select-alquiler-by-id=SELECT * FROM Alquiler WHERE id_alquiler = ?
select-embarcaciones-disponibles-api=SELECT * FROM Embarcacion WHERE matricula NOT IN (SELECT matricula_embarcacion_fk FROM Alquiler WHERE fecha_inicio <= ? AND fecha_fin >= ?) AND matricula NOT IN (SELECT matricula_embarcacion_fk FROM Reserva WHERE fecha_actividad BETWEEN ? AND ?)

# --- Gestión de Pasajeros ---
insert-socio-alquiler-single = INSERT INTO Socio_Alquiler (id_alquiler_fk, dni_socio_fk) VALUES (?, ?)
delete-socio-alquiler-single = DELETE FROM Socio_Alquiler WHERE id_alquiler_fk = ? AND dni_socio_fk = ?
select-pasajeros-by-alquiler = SELECT dni_socio_fk FROM Socio_Alquiler WHERE id_alquiler_fk = ?

# --- Borrar todos los pasajeros de un alquiler ---
delete-pasajeros-alquiler = DELETE FROM Socio_Alquiler WHERE id_alquiler_fk = ?

# --- CORREGIDO MAYÚSCULA EN 'Alquiler' ---
delete-alquiler = DELETE FROM Alquiler WHERE id_alquiler = ? AND fecha_inicio > CURRENT_DATE

# -- Consultas Gestión de Socios
update-socio = UPDATE Socio SET nombre = ?, apellidos = ?, fecha_nacimiento = ?, direccion = ?, fecha_inscripcion = ?, tiene_titulo_patron = ?, id_inscripcion_fk = ? WHERE dni = ?
select-inscripcion-by-id = SELECT * FROM Inscripcion WHERE id_inscripcion = ?
update-socio-desvincular = UPDATE Socio SET id_inscripcion_fk = NULL WHERE dni = ?
update-socios-desvincular-todos = UPDATE Socio SET id_inscripcion_fk = NULL WHERE id_inscripcion_fk = ?
delete-inscripcion = DELETE FROM Inscripcion WHERE id_inscripcion = ?
delete-socio = DELETE FROM Socio WHERE dni = ?

# -- Consultas de EmbarcacionRepository --
update-embarcacion=UPDATE Embarcacion SET nombre = ?, tipo = ?, plazas = ?, dimensiones = ? WHERE matricula = ?
count-alquileres-embarcacion=SELECT COUNT(*) FROM Alquiler WHERE matricula_embarcacion_fk = ?
count-reservas-embarcacion=SELECT COUNT(*) FROM Reserva WHERE matricula_embarcacion_fk = ?
delete-embarcacion=DELETE FROM Embarcacion WHERE matricula = ?

# -- Consultas de PatronRepository --
update-patron=UPDATE Patron SET nombre = ?, apellidos = ?, fecha_nacimiento = ?, fecha_expedicion_titulo = ? WHERE dni = ?
delete-patron=DELETE FROM Patron WHERE dni = ?